function [eLims, iLims] = setCustomYlim(eLims,iLims)

inputFig = figure('Name', 'Custom Y limits',...
    'NumberTitle', 'off',...
    'WindowStyle', 'modal',...
    'MenuBar','none',...
    'Units', 'normalized',...
    'Position', [0.2, 0.3, 0.3, 0.2]);
ephysPanel = uipanel(inputFig,...
    'Title', 'Ephys limits',...
    'Position', [0, 0.15, 0.495, 0.85]);
uicontrol(ephysPanel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.1, 0.9, 0.35, 0.075],...
    'String', 'Raw Y lims:');
eRawLimsEdit1 = uicontrol(ephysPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.5, 0.9, 0.2, 0.075],...
    'String', num2str(eLims(1,1)));
eRawLimsEdit2 = uicontrol(ephysPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.75, 0.9, 0.2, 0.075],...
    'String', num2str(eLims(1,2)));
uicontrol(ephysPanel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.1, 0.7, 0.35, 0.075],...
    'String', 'Bandpass Y lims:');
eBpLimsEdit1 = uicontrol(ephysPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.5, 0.7, 0.2, 0.075],...
    'String', num2str(eLims(2,1)));
eBpLimsEdit2 = uicontrol(ephysPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.75, 0.7, 0.2, 0.075],...
    'String', num2str(eLims(2,2)));
uicontrol(ephysPanel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.1, 0.5, 0.35, 0.075],...
    'String', 'Power Y lims:');
ePowLimsEdit1 = uicontrol(ephysPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.5, 0.5, 0.2, 0.075],...
    'String', num2str(eLims(3,1)));
ePowLimsEdit2 = uicontrol(ephysPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.75, 0.5, 0.2, 0.075],...
    'String', num2str(eLims(3,2)));

imagingPanel = uipanel(inputFig,...
    'Title', 'Imaging limits',...
    'Position', [0.505, 0.15, 0.495, 0.85]);
uicontrol(imagingPanel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.1, 0.9, 0.35, 0.075],...
    'String', 'Raw Y lims:');
iRawLimsEdit1 = uicontrol(imagingPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.5, 0.9, 0.2, 0.075],...
    'String', num2str(iLims(1,1)));
iRawLimsEdit2 = uicontrol(imagingPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.75, 0.9, 0.2, 0.075],...
    'String', num2str(iLims(1,2)));
uicontrol(imagingPanel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.1, 0.7, 0.35, 0.075],...
    'String', 'Smoothed Y lims:');
iSmoothLimsEdit1 = uicontrol(imagingPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.5, 0.7, 0.2, 0.075],...
    'String', num2str(iLims(2,1)));
iSmoothLimsEdit2 = uicontrol(imagingPanel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.75, 0.7, 0.2, 0.075],...
    'String', num2str(iLims(2,2)));

uicontrol(inputFig,...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.75, 0, 0.2, 0.1],...
    'String', 'Save changes',...
    'Callback', @(h,e) saveButtCB)

uiwait

    function saveButtCB
        eLims = [str2double(eRawLimsEdit1.String), str2double(eRawLimsEdit2.String);...
            str2double(eBpLimsEdit1.String), str2double(eBpLimsEdit2.String);...
            str2double(ePowLimsEdit1.String), str2double(ePowLimsEdit2.String)];

        iLims = [str2double(iRawLimsEdit1.String), str2double(iRawLimsEdit2.String);...
            str2double(iSmoothLimsEdit1.String), str2double(iSmoothLimsEdit2.String)];

        uiresume
        delete(inputFig)
    end
end